export const SOCKET_CONNECT_REQUEST = 'SOCKET_CONNECT_REQUEST';
export const SOCKET_CONNECT_SUCCESS = 'SOCKET_CONNECT_SUCCESS';
export const SOCKET_CONNECT_FAILED = 'SOCKET_CONNECT_FAILED';
export const SOCKET_DISCONNECT = 'SOCKET_DISCONNECT';
